#!/bin/bash

### This script is called after the user uninstalls the application.

WIZARD_DATA_ACTION="$wizard_data_action"

if [ "$WIZARD_DATA_ACTION" = "delete" ]; then
    rm -rf "${TRIM_PKGVAR}"
fi

exit 0
